### ISSUE TITLE
Reshape error

### ISSUE THREAD

**Issue by semperos** [briangu/klongpy#10]
I observe the following behavior in KlongPy v0.6.8:

```
?> [3 3]:^"abcd"
["abc" "dab" "cda"]
?> [2 2]:^"abcd"
Error: ('sequence item 0: expected str instance, numpy.ndarray found',)
```

Here is the fuller stack trace with the `-v` flag set:

```
?> [2 2]:^"abcd"
Traceback (most recent call last):
  File "/opt/homebrew/bin/kgpy", line 179, in repl_eval
    r = klong(p)
        ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/klongpy/interpreter.py", line 653, in __call__
    r = self.exec(x)
        ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/klongpy/interpreter.py", line 664, in exec
    return [self.call(y) for y in self.prog(x)[1]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/klongpy/interpreter.py", line 664, in <listcomp>
    return [self.call(y) for y in self.prog(x)[1]]
            ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/klongpy/interpreter.py", line 596, in call
    return self.eval(KGCall(x.a, x.args, x.arity) if isinstance(x, KGFn) else x)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/klongpy/interpreter.py", line 622, in eval
    return f(_x) if x.a.arity == 1 else f(_x, _y)
                                        ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/klongpy/dyads.py", line 835, in eval_dyad_reshape
    return "".join(r) if j else r
           ^^^^^^^^^^
TypeError: sequence item 0: expected str instance, numpy.ndarray found
Error: ('sequence item 0: expected str instance, numpy.ndarray found',)
```

I observe the following with arguments of different sizes:

```
?> [2 2]:^"a"
["aa" "aa"]
?> [2 2]:^"ab"
["ab" "ab"]
?> [2 2]:^"abc"
["ab" "ca"]
?> [2 2]:^"abcd"
Error: ('sequence item 0: expected str instance, numpy.ndarray found',)
```

**Comment by briangu** [comment]
https://github.com/briangu/klongpy/pull/23
